package p000;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class amvt {

    /* renamed from: a */
    public static final batz f46466a = batz.m37363m(blwh.OPEN_SHARE_SHEET_WITH_1P_TARGETS_FROM_ALBUM, blwh.OPEN_SHARE_SHEET_WITH_3P_TARGETS_FROM_ALBUM);

    /* renamed from: b */
    public static final batz f46467b = batz.m37363m(blwh.OPEN_SHARE_SHEET_1P_TARGETS_FROM_MEMORY, blwh.OPEN_SHARE_SHEET_3P_TARGETS_FROM_MEMORY);

    /* renamed from: c */
    public static final batz f46468c = batz.m37363m(blwh.OPEN_SHARE_SHEET_WITH_1P_TARGETS_FROM_LSV, blwh.OPEN_SHARE_SHEET_WITH_3P_TARGETS_FROM_LSV);

    /* renamed from: d */
    public static final batz f46469d = batz.m37369s(blwh.OPEN_SHARE_SHEET_WITH_1P_TARGETS_FROM_PHOTO_ONE_UP, blwh.OPEN_SHARE_SHEET_FROM_PHOTO_ONE_UP, blwh.OPEN_SHARE_SHEET_WITH_1P_TARGETS_FROM_PHOTO_GRID, blwh.OPEN_SHARE_SHEET_WITH_3P_TARGETS_FROM_PHOTO_GRID, blwh.OPEN_SHARE_SHEET_1P_TARGETS_FROM_INTENT, blwh.OPEN_SHARE_SHEET_3P_TARGETS_FROM_INTENT, blwh.OPEN_SHARE_SHEET_WITH_1P_TARGETS_FROM_LSV, blwh.OPEN_SHARE_SHEET_WITH_3P_TARGETS_FROM_LSV);

    /* renamed from: e */
    public static final batz f46470e = batz.m37365o(blwh.OPEN_SHARE_SHEET_WITH_1P_TARGETS_FROM_PHOTO_ONE_UP, blwh.OPEN_SHARE_SHEET_WITH_1P_TARGETS_FROM_PHOTO_GRID, blwh.OPEN_SHARE_SHEET_1P_TARGETS_FROM_INTENT, blwh.OPEN_SHARE_SHEET_1P_TARGETS_FROM_MEMORY);

    /* renamed from: f */
    public static final batz f46471f = batz.m37364n(blwh.OPEN_SHARE_SHEET_3P_TARGETS_FROM_MEMORY, blwh.OPEN_SHARE_SHEET_WITH_3P_TARGETS_FROM_ALBUM, blwh.OPEN_SHARE_SHEET_WITH_3P_TARGETS_FROM_LSV);

    /* renamed from: g */
    public static final batz f46472g = batz.m37364n(blwh.START_3RD_PARTY_APP_FROM_SHARE_SHEET, blwh.START_3RD_PARTY_APP_BY_SHARING_FILE_FROM_SHARE_SHEET, blwh.START_3RD_PARTY_APP_BY_SHARING_LINK_FROM_SHARE_SHEET);
}
