package p000;

/* compiled from: PG */
/* loaded from: classes5.dex */
public enum axto {
    NONE,
    SUCCESS,
    FAILED_UNKNOWN,
    FAILED_ACCOUNT_NOT_LOGGED_IN,
    FAILED_CORRUPT_CACHE,
    FAILED_DATA_FRESH,
    FAILED_NETWORK,
    FAILED_PEOPLE_API_RESPONSE_EMPTY,
    FAILED_PEOPLE_API_INVALID_ARGUMENT,
    FAILED_GMSCORE_CONNECTION_ERROR,
    FAILED_GMSCORE_EMPTY_QUERY,
    FAILED_TIMEOUT,
    FAILED_CANCELED,
    FAILED_INTERRUPTED,
    FAILED_EXPERIMENTS_CHANGED,
    FAILED_NOT_IMPLEMENTED,
    FAILED_TO_READ_FILE,
    SKIPPED,
    FAILED_HTTP_SERVER_ERROR,
    FAILED_REMOTE,
    FAILED_UNKNOWN_CUSTOM_PROVIDER,
    FAILED_MISSING_SCHEDULED_EXECUTOR
}
