package p000;

/* compiled from: PG */
/* loaded from: classes5.dex */
public enum bcxw implements bfit {
    NOTIFICATION_FAILURE_UNSPECIFIED(0),
    BAD_CHANNEL(1),
    CHANNEL_NOT_FOUND(34),
    CHANNEL_BLOCKED(35),
    USER_BLOCKED(6),
    BAD_PAYLOAD(2),
    INSUFFICIENT_DATA_NO_TITLE(7),
    INSUFFICIENT_DATA_NO_TEXT(8),
    DROPPED_BY_VERSION(41),
    DROPPED_OLDER_THAN_FIRST_REGISTRATION(51),
    THREAD_ALREADY_DISMISSED(53),
    DROPPED_BY_STATE(65),
    DROPPED_EXPIRED(66),
    MAX_NOTIFICATION_COUNT_REACHED(42),
    DROPPED_BY_CLIENT(3),
    INVALID_USER(4),
    RECIPIENT_NOT_FOUND(9),
    RECIPIENT_NOT_REGISTERED(10),
    RECIPIENT_INVALID_CREDENTIALS(25),
    FAILED_TO_DOWNLOAD_IMAGE(11),
    FAILED_TO_FETCH_NOTIFICATIONS_BY_ID(37),
    FAILED_TO_FETCH_LATEST_NOTIFICATIONS(12),
    FAILED_TO_FETCH_UPDATED_NOTIFICATIONS(13),
    FAILED_TO_REGISTER(14),
    FAILED_TO_REGISTER_OTHER_ACCOUNT(63),
    FAILED_TO_UNREGISTER(15),
    FAILED_TO_UPDATE_THREAD_STATE(16),
    FAILED_TO_UPDATE_THREAD_STATE_BY_TOKEN(17),
    FAILED_TO_FETCH_SUBSCRIPTIONS(38),
    FAILED_TO_SUBSCRIBE_TO_TOPICS(18),
    FAILED_TO_UNSUBSCRIBE_FROM_TOPICS(19),
    FAILED_TO_FETCH_PREFS(20),
    FAILED_TO_UPDATE_PREFS(21),
    FAILED_TO_ACKNOWLEDGE(22),
    FAILED_TO_FETCH_MULTI_USER_BADGE_COUNT(39),
    FAILED_TO_REGISTER_LOCATION(54),
    FAILED_TO_REGISTER_PUSHKIT(55),
    FAILED_TO_REGISTER_LIVE_ACTIVITY(62),
    FAILED_TO_REGISTER_LIVE_ACTIVITY_PTS(67),
    FAILED_TO_COUNT_THREADS(56),
    FAILED_TO_UPDATE_ALL_THREAD_STATES(59),
    FAILED_TO_POST_LOCAL_NOTIFICATION(64),
    FAILED_TO_GET_IID(23),
    INCONSISTENT_COUNT(24),
    UPSTREAM_TASK_TOO_BIG(26),
    UPSTREAM_UPDATE_THREAD_STATE_TASK_PARSE_ERROR(27),
    UPSTREAM_UNKNOWN_SEND_ERROR(28),
    UPSTREAM_INVALID_PARAMETERS(29),
    UPSTREAM_TOO_BIG(30),
    UPSTREAM_SENT_BUT_NOT_IN_TASK_TABLE(31),
    FAILED_ACCOUNT_DATA_CLEANUP(36),
    DATABASE_ERROR(40),
    FAILED_TO_APPLY_CUSTOMIZATION(52),
    UPSTREAM_ZOMBIE_FOUND(32),
    UPSTREAM_TOO_MANY_PENDING_MESSAGES(33),
    SDK_DOES_NOT_SUPPORT(5),
    FAILED_TO_DECRYPT_PAYLOAD_FALLBACK_TO_PLACEHOLDER(57),
    FAILED_TO_DECRYPT_PAYLOAD_NO_PLACEHOLDER(58),
    FAILED_TO_DECOMPRESS_FALLBACK_TO_PLACEHOLDER(60),
    FAILED_TO_DECOMPRESS(61);


    /* renamed from: ai */
    public final int f89823ai;

    bcxw(int i) {
        this.f89823ai = i;
    }

    @Override // p000.bfit
    /* renamed from: a */
    public final int mo6948a() {
        return this.f89823ai;
    }

    @Override // java.lang.Enum
    public final String toString() {
        return Integer.toString(this.f89823ai);
    }
}
