package p000;

import p047j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final /* synthetic */ class mis implements yes {

    /* renamed from: a */
    private final /* synthetic */ int f159566a;

    public /* synthetic */ mis(int i) {
        this.f159566a = i;
    }

    @Override // p000.yes
    /* renamed from: a */
    public final Object mo9922a() {
        _3138 m6907O;
        _3138 m6907O2;
        switch (this.f159566a) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
                return false;
            case 5:
                return new nod(0);
            case 6:
                return baug.m37400l(_319.class, new _371());
            case 7:
                return new nod(1);
            case 8:
                return new aiyz(new acfg(null));
            case 9:
                return new aiyz(new mex(7));
            case 10:
                return new aiyz(new mez(13));
            case 11:
                return new aiyz(new orm(18));
            case 12:
                return new aiyz(new mex(6));
            case 13:
                return new aiyz(new mez(3));
            case 14:
                return new aiyz(new mez(12));
            case 15:
                return C1124um.m70035i();
            case 16:
                return Optional.empty();
            case 17:
                return _3138.m6907O(blwh.FREE_UP_SPACE_DELETE_DEVICE_COPIES, blwh.RESTORE_LOCAL, blwh.RESTORE_REMOTE, blwh.TRASH_LOCAL, blwh.TRASH_REMOTE, blwh.REMOTE_PERMANENT_DELETE, blwh.WALLART_CHECKOUT, blwh.PHOTOBOOKS_CHECKOUT, blwh.COPY_TO_FOLDER, blwh.MOVE_TO_FOLDER, blwh.OPEN_PHOTO_ONE_UP_FROM_CAMERA_REVIEW, blwh.CREATE_SHARED_ALBUM_FOR_MEDIA_SHARE_API, blwh.VIDEOEDITOR_SAVE, blwh.PROBE_TRANSCODE, blwh.EXPORT_VIDEO_FOR_MEMORY, blwh.PHOTOEDITOR_APPLY_MAGIC_EDITOR_EFFECT, blwh.OPEN_SHARE_SHEET_1P_TARGETS_FROM_INTENT, blwh.OPEN_SHARE_SHEET_3P_TARGETS_FROM_INTENT, blwh.SEND_ITEMS_TO_NEW_CONVERSATION_ONLINE, blwh.SEND_ITEMS_TO_NEW_CONVERSATION_OPTIMISTIC, blwh.SEND_ITEMS_TO_EXISTING_CONVERSATION_ONLINE, blwh.SEND_ITEMS_TO_EXISTING_CONVERSATION_OPTIMISTIC, blwh.ADD_COLLECTION_COMMENT_ONLINE, blwh.ADD_COLLECTION_COMMENT_OPTIMISTIC, blwh.ADD_PHOTO_COMMENT_ONLINE, blwh.ADD_PHOTO_COMMENT_OPTIMISTIC, blwh.ADD_COLLECTION_HEART_ONLINE, blwh.ADD_COLLECTION_HEART_OPTIMISTIC, blwh.ADD_PHOTO_HEART_ONLINE, blwh.ADD_PHOTO_HEART_OPTIMISTIC, blwh.ADD_PHOTOS_TO_ALBUM_ONLINE, blwh.ADD_PHOTOS_TO_ALBUM_OPTIMISTIC, blwh.SAVE_SHARED_ITEMS_FROM_PHOTO_ONE_UP_ONLINE, blwh.SAVE_SHARED_ITEMS_FROM_PHOTO_ONE_UP_OPTIMISTIC, blwh.SAVE_SHARED_ITEMS_FROM_ACTIVITY_FEED_ONLINE, blwh.SAVE_SHARED_ITEMS_FROM_ACTIVITY_FEED_OPTIMISTIC, blwh.SAVE_SHARED_ITEMS_FROM_ALBUM_ONE_UP_ONLINE, blwh.SAVE_SHARED_ITEMS_FROM_ALBUM_ONE_UP_OPTIMISTIC, blwh.CREATE_ALBUM_ONLINE, blwh.CREATE_SHARED_ALBUM_ONLINE, blwh.CREATE_SHARED_ALBUM_OPTIMISTIC, blwh.CREATE_TALLAC_ENVELOPE, blwh.SEND_ALBUM_TO_CONTACTS_ONLINE, blwh.ACCEPT_PARTNER_SHARE_COLLECTION_SUGGESTION_ONLINE, blwh.ACCEPT_PARTNER_SHARE_COLLECTION_SUGGESTION_OPTIMISTIC, blwh.JOIN_SHARED_ALBUM_FROM_LINK_ONLINE, blwh.JOIN_SHARED_ALBUM_FROM_LINK_OPTIMISTIC, blwh.LEAVE_SHARED_ALBUM_ONLINE, blwh.LEAVE_SHARED_ALBUM_OPTIMISTIC, blwh.DOWNLOAD_PHOTO_ONE_UP, blwh.DOWNLOAD_VIDEO_ONE_UP, blwh.DOWNLOAD_MOTION_PHOTO_ONE_UP, blwh.REBUILD_DATE_HEADERS);
            case 18:
                m6907O = _3138.m6907O(blwh.TRASH_REMOTE, blwh.RESTORE_REMOTE, blwh.REMOTE_METADATA_SYNC, blwh.ADD_COLLECTION_COMMENT_OPTIMISTIC, blwh.ADD_COLLECTION_HEART_OPTIMISTIC, blwh.ADD_PHOTO_COMMENT_OPTIMISTIC, blwh.ADD_PHOTO_HEART_OPTIMISTIC, blwh.ADD_PHOTOS_TO_ALBUM_OPTIMISTIC, blwh.BACKUP_COMPLETE_FREE_UP_SPACE_ELIGIBLE, blwh.BACKUP_NOW_STARTED_BACKUP, blwh.BACK_UP_NOW_TAPPED_CONFIRMATION_SHOWN, blwh.CAMERA_REVIEW_PROCESSED_PHOTO, blwh.COPY_TO_FOLDER, blwh.DELETE_FROM_DEVICE_CONFIRMED_FILES_DELETED, blwh.DELETE_FROM_DEVICE_OPEN_CONFIRMATION, blwh.FREE_UP_SPACE_DELETE_DEVICE_COPIES, blwh.FREE_UP_SPACE_OPEN_FULL_SCREEN_EXPERIENCE, blwh.FREE_UP_SPACE_REQUEST_PERMISSIONS_FOR_MEDIA, blwh.INTEGRITY_TEST_START_END_ZERO_LATENCY, blwh.INTEGRITY_TEST_START_END_ONE_SECOND_LATENCY, blwh.INTEGRITY_TEST_START_END_TEN_SECONDS_LATENCY, blwh.INTEGRITY_TEST_START_END_ONE_MINUTE_LATENCY, blwh.LOAD_LOCAL_VIDEO_FOR_PLAYBACK, blwh.LOAD_SHARING_PAGE_BADGE, blwh.LOCKED_FOLDER_AUTHENTICATE, blwh.MEMORIES_CHECK_AVAILABLE, blwh.MEMORIES_OPEN_FROM_GRID, blwh.MEMORIES_OPEN_FROM_NOTIFICATION, blwh.MOVE_TO_FOLDER, blwh.OPEN_APP_TO_AUTOBACKUP_BAR, blwh.OPEN_APP_TO_FRESH_GRID, blwh.OPEN_APP_TO_ONBOARDING, blwh.OPEN_CONTACT_PICKER_FOR_SHARED_LIBRARIES, blwh.OPEN_CREATE_ALBUM_SCREEN, blwh.OPEN_CREATE_SHARED_ALBUM_SCREEN, blwh.OPEN_DEVICE_FOLDER, blwh.OPEN_DEVICE_FOLDERS_GRID, blwh.OPEN_INFO_PANEL_WITH_ACTIONS, blwh.OPEN_INFO_PANEL_WITH_LENS, blwh.OPEN_INFO_PANEL_WITH_LENS_VISUAL_ENTITY, blwh.OPEN_INFO_PANEL_WITH_LOCATION, blwh.OPEN_INFO_PANEL_WITH_MOMENTS, blwh.OPEN_LIBRARY_TAB, blwh.OPEN_LIVE_ALBUM_PEOPLE_PICKER, blwh.OPEN_NEW_SHARE_COMPOSE_STATE, blwh.OPEN_PHOTO_ONE_UP_FROM_CAMERA_REVIEW, blwh.OPEN_PHOTO_PICKER_FROM_ALBUM, blwh.OPEN_PHOTO_PICKER_FROM_CONVERSATION, blwh.OPEN_SEARCH_TAB, blwh.OPEN_SELECTIVE_BACKUP_GRID, blwh.OPEN_SHARE_SHEET_FROM_PHOTO_ONE_UP, blwh.OPEN_SHARING_PAGE, blwh.PHOTOEDITOR_SAVE, blwh.PHOTOEDITOR_SELECT_EDIT, blwh.PRINTING_BASIC_EDIT, blwh.RESTORE_LOCAL, blwh.SCRUB_FINISHED_SCREEN_LOADED, blwh.SEND_ITEMS_TO_NEW_CONVERSATION_OPTIMISTIC, blwh.SHOW_SAVE_BUTTON_ON_ACTIVITY_FEED, blwh.STOMO_OPEN_CHECKOUT_UI, blwh.TOP_SHOT_OPEN, blwh.TRASH_CONFIRMED_ITEM_REMOVED, blwh.TRASH_LOCAL, blwh.TRASH_OPEN_CONFIRMATION, blwh.VIDEOEDITOR_EDIT, blwh.VIDEOEDITOR_SAVE, blwh.VIDEOEDITOR_STABILIZE, blwh.VIDEOEDITOR_SPOTLIGHT_PRECOMPUTE, blwh.VIDEOEDITOR_SPOTLIGHT_MODEL_DOWNLOAD, blwh.VIDEOEDITOR_GET_VIDEO_EDITING_HINTS);
                return m6907O;
            case 19:
                return _3138.m6907O(bgch.f102662d, bgrw.f104673U, bgrw.f104706aa, bgrw.f104751h, bgrw.f104755l, bgrw.f104720ao, bgrw.f104722aq, bgrw.f104760q, bgrw.f104761r, bgrw.f104762s, bgrw.f104653A, bgrw.f104654B, bhcd.f106025o);
            default:
                m6907O2 = _3138.m6907O(blwh.TRASH_REMOTE, blwh.RESTORE_REMOTE, blwh.REMOTE_METADATA_SYNC, blwh.ADD_COLLECTION_COMMENT_OPTIMISTIC, blwh.ADD_COLLECTION_HEART_OPTIMISTIC, blwh.ADD_PHOTO_COMMENT_OPTIMISTIC, blwh.ADD_PHOTO_HEART_OPTIMISTIC, blwh.ADD_PHOTOS_TO_ALBUM_OPTIMISTIC, blwh.BACKUP_COMPLETE_FREE_UP_SPACE_ELIGIBLE, blwh.BACKUP_NOW_STARTED_BACKUP, blwh.BACK_UP_NOW_TAPPED_CONFIRMATION_SHOWN, blwh.CAMERA_REVIEW_PROCESSED_PHOTO, blwh.COPY_TO_FOLDER, blwh.DELETE_FROM_DEVICE_CONFIRMED_FILES_DELETED, blwh.DELETE_FROM_DEVICE_OPEN_CONFIRMATION, blwh.FREE_UP_SPACE_DELETE_DEVICE_COPIES, blwh.FREE_UP_SPACE_OPEN_FULL_SCREEN_EXPERIENCE, blwh.FREE_UP_SPACE_REQUEST_PERMISSIONS_FOR_MEDIA, blwh.INTEGRITY_TEST_START_END_ZERO_LATENCY, blwh.INTEGRITY_TEST_START_END_ONE_SECOND_LATENCY, blwh.INTEGRITY_TEST_START_END_TEN_SECONDS_LATENCY, blwh.INTEGRITY_TEST_START_END_ONE_MINUTE_LATENCY, blwh.LOAD_LOCAL_VIDEO_FOR_PLAYBACK, blwh.LOAD_SHARING_PAGE_BADGE, blwh.LOCKED_FOLDER_AUTHENTICATE, blwh.MEMORIES_CHECK_AVAILABLE, blwh.MEMORIES_OPEN_FROM_GRID, blwh.MEMORIES_OPEN_FROM_NOTIFICATION, blwh.MOVE_TO_FOLDER, blwh.OPEN_APP_TO_AUTOBACKUP_BAR, blwh.OPEN_APP_TO_FRESH_GRID, blwh.OPEN_APP_TO_ONBOARDING, blwh.OPEN_CONTACT_PICKER_FOR_SHARED_LIBRARIES, blwh.OPEN_CREATE_ALBUM_SCREEN, blwh.OPEN_CREATE_SHARED_ALBUM_SCREEN, blwh.OPEN_DEVICE_FOLDER, blwh.OPEN_DEVICE_FOLDERS_GRID, blwh.OPEN_INFO_PANEL_WITH_ACTIONS, blwh.OPEN_INFO_PANEL_WITH_LENS, blwh.OPEN_INFO_PANEL_WITH_LENS_VISUAL_ENTITY, blwh.OPEN_INFO_PANEL_WITH_LOCATION, blwh.OPEN_INFO_PANEL_WITH_MOMENTS, blwh.OPEN_LIBRARY_TAB, blwh.OPEN_LIVE_ALBUM_PEOPLE_PICKER, blwh.OPEN_NEW_SHARE_COMPOSE_STATE, blwh.OPEN_PHOTO_ONE_UP_FROM_CAMERA_REVIEW, blwh.OPEN_PHOTO_PICKER_FROM_ALBUM, blwh.OPEN_PHOTO_PICKER_FROM_CONVERSATION, blwh.OPEN_SEARCH_TAB, blwh.OPEN_SELECTIVE_BACKUP_GRID, blwh.OPEN_SHARE_SHEET_FROM_PHOTO_ONE_UP, blwh.OPEN_SHARING_PAGE, blwh.PHOTOEDITOR_SAVE, blwh.PHOTOEDITOR_SELECT_EDIT, blwh.PRINTING_BASIC_EDIT, blwh.RESTORE_LOCAL, blwh.SCRUB_FINISHED_SCREEN_LOADED, blwh.SEND_ITEMS_TO_NEW_CONVERSATION_OPTIMISTIC, blwh.SHOW_SAVE_BUTTON_ON_ACTIVITY_FEED, blwh.STOMO_OPEN_CHECKOUT_UI, blwh.TOP_SHOT_OPEN, blwh.TRASH_CONFIRMED_ITEM_REMOVED, blwh.TRASH_LOCAL, blwh.TRASH_OPEN_CONFIRMATION, blwh.VIDEOEDITOR_EDIT, blwh.VIDEOEDITOR_SAVE, blwh.VIDEOEDITOR_STABILIZE, blwh.VIDEOEDITOR_SPOTLIGHT_PRECOMPUTE, blwh.VIDEOEDITOR_SPOTLIGHT_MODEL_DOWNLOAD, blwh.VIDEOEDITOR_GET_VIDEO_EDITING_HINTS);
                return m6907O2;
        }
    }
}
