package p000;

/* compiled from: PG */
/* loaded from: classes3.dex */
public enum yvh {
    MEDIA_BEING_PROCESSED,
    MEDIA_FEATURES_LOAD_FAILURE,
    MEDIA_STORE_INSERTION_FAILURE,
    MEDIA_STORE_SCAN_FAILURE,
    FILE_NOT_FOUND,
    NO_CONNECTIVITY,
    GENERIC_IO_EXCEPTION,
    NONE,
    REMOTE_DELETION_RPC_FAILURE,
    REMOTE_DELETION_GENERIC_FAILURE,
    UNKNOWN_FAILURE
}
